### ISSUE TITLE
Bug: render info not working

### ISSUE THREAD

**Issue by jburel** [ome/omero-cli-render#5]
```
bin/omero render info Image:6254
Previous session expired for trainer-1 on localhost:4064
Server: [localhost:4064]
Username: [trainer-1]
Password:
Created session b8a (trainer-1@localhost:4064). Idle timeout: 10 min. Current group: Lab1
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero/cli.py", line 1615, in argv
    cli.invoke(args[1:])
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero/cli.py", line 1090, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero/cli.py", line 1167, in onecmd
    self.execute(line, previous_args)
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero/cli.py", line 1249, in execute
    args.func(args)
  File "/usr/lib/python2.7/site-packages/omero_cli_render.py", line 342, in info
    ro = RenderObject(img)
  File "/usr/lib/python2.7/site-packages/omero_cli_render.py", line 207, in __init__
    image.getChannels(noRE=True))
  File "/usr/lib/python2.7/site-packages/omero_cli_render.py", line 206, in <lambda>
    self.channels = map(lambda x: ChannelObject(x),
  File "/usr/lib/python2.7/site-packages/omero_cli_render.py", line 109, in __init__
    self.init_from_channel(channel)
  File "/usr/lib/python2.7/site-packages/omero_cli_render.py", line 117, in init_from_channel
    self.min = channel.getWindowMin()
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero/gateway/__init__.py", line 7446, in getWindowMin
    return si.getGlobalMin().val
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero_model_StatsInfoI.py", line 138, in getGlobalMin
    self.errorIfUnloaded()
  File "/opt/omero/server/OMERO.server-5.4.1-ice36-b75/lib/python/omero_model_StatsInfoI.py", line 39, in errorIfUnloaded
    raise _omero.UnloadedEntityException("Object unloaded:"+str(self))
omero.UnloadedEntityException: Object unloaded:object #0 (::omero::model::StatsInfo)
{
    _id = object #1 (::omero::RLong)
    {
        _val = 12053
    }
    _details = <nil>
    _loaded = False
    _version = <nil>
    _globalMin = <nil>
    _globalMax = <nil>
}
```

**Comment by jburel** [comment]
https://github.com/ome/omero-cli-render/pull/3

**Comment by sbesson** [comment]
Closing as this should have been addressing by #7 and released.
